services:
  mysql:
    image: mysql:8.0.16
    container_name: forum_mysql
    environment:
        MYSQL_ROOT_PASSWORD: mysql
    ports:
        - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql