services:
  mysql:
    image: mysql:8.0.16
    container_name: forum_mysql
    environment:
        MYSQL_ROOT_PASSWORD: mysql
    ports:
        - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        

  redis:
    image: redis:3.2
    container_name: forum_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
    driver: local
